theme = "typo"
baseURL = 'https://Fruitesque.github.io/'
languageCode = 'en-us'
defaultContentLanguage = 'en-us'
title = '大胆的弗伦'
[params]
  author = "andata"
  homePostsNumber = 3

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

# Default config
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

[markup]
[markup.highlight]
noClasses = false
